apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: featsrini
  namespace: argocd
spec:
  sourceRepos:
  - '*'
  destinations:
  - namespace: '*'
    server: https://mega-featsrini-kubernetes-dns-a01ec178.hcp.westeurope.azmk8s.io:443
  - namespace: '*'
    server: https://kubernetes.default.svc
  clusterResourceWhitelist:
  - group: '*'
    kind: '*'