apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: cert-manager
  namespace: argocd
spec:
  generators:
  - clusters:
      selector:
        matchLabels:
          env: dev
  # - git:
  #     repoURL: https://github.com/c3JpbmkK/turbo-octo-dollop.git
  #     revision: HEAD
  #     directories:
  #     - path: projects/tracer
  template:
    metadata:
      name: cluster-tracer
    spec:
      project: tracer
      source:
        repoURL: https://github.com/c3JpbmkK/turbo-octo-dollop.git
        targetRevision: HEAD
        path: projects/tracer
        directory:
          recurse: true
      destination:
        server: https://kubernetes.default.svc
        namespace: argocd
      syncPolicy:
        syncOptions:
        - CreateNamespace=true
        - ApplyOutOfSyncOnly=true
        - PrunePropagationPolicy=foreground
        automated:
          prune: true
          selfHeal: true
          allowEmpty: true
