apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: westeurope-applicationset
  namespace: argocd
spec:
  generators:
  - matrix:
      generators:
        - git:
            repoURL: https://github.com/c3JpbmkK/turbo-octo-dollop.git
            revision: 3-apps
            directories:
            - path: apps/*
        - clusters:
            selector:
              matchExpressions:
                - key: tenant
                  operator: In
                  values:
                    - liquid-reply
                - key: env
                  operator: In
                  values:
                    - dev
            values:
              region: westeurope
  template:
    metadata:
      name: '{{ name }}-{{ path.basenameNormalized }}'
      labels:
        app: '{{ path.basenameNormalized }}'
        cluster: '{{ name }}'
        topology.kubernetes.io/region: '{{ values.region }}'
      # WARNING: DELETION WILL PROPAGATE IF THIS FINALIZER IS USED
      finalizers:
        - resources-finalizer.argocd.argoproj.io
    spec:
      project: '{{ name }}'
      source:
        repoURL: https://github.com/c3JpbmkK/turbo-octo-dollop.git
        targetRevision: 3-apps
        path: 'apps/{{ path.basenameNormalized }}'
        helm:
          valueFiles:
            - values.yaml
      destination:
        name: '{{ name }}'
        namespace: '{{ path.basenameNormalized }}'
      syncPolicy:
        syncOptions:
        - CreateNamespace=true
        - ApplyOutOfSyncOnly=true
        # WARNING: DELETION WILL PROPAGATE IF THIS OPTION IS USED TOGETHER WITH FINALIZER
        - PrunePropagationPolicy=foreground
        automated:
          prune: true
          selfHeal: true
          allowEmpty: true
