apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: '{{ .Release.Name }}'
  namespace: '{{ .Release.Namespace }}'
spec:
  secretName: '{{ .Release.Name }}-tls'
  secretTemplate:
    annotations: {}
    labels: {}

  # https://golang.org/pkg/time/#ParseDuration
  duration: 2160h
  renewBefore: 360h

  dnsNames:
    - 'argocd.{{ .Values.clusterName }}.{{ .Values.clusterDomain }}'

  issuerRef:
    name: '{{ .Values.clusterName }}-cert-manager-http01-clusterissuer'
    kind: ClusterIssuer
    group: cert-manager.io