apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: tracer-application-set
  namespace: argocd
spec:
  generators:
  - matrix:
      generators:
      - clusters:
          selector:
            matchLabels:
              tenant: liquid-reply
      - git:
          repoURL: https://github.com/c3JpbmkK/turbo-octo-dollop.git
          revision: main
          directories:
          - path: clusters/tracer/*
  template:
    metadata:
      name: "{{name}}-applicationset-{{path.basenameNormalized}}"
    spec:
      project: "{{name}}"
      source:
        repoURL: https://github.com/c3JpbmkK/turbo-octo-dollop.git
        targetRevision: main
        path: "clusters/{{name}}/{{path.basenameNormalized}}"
        helm:
          valueFiles:
          - https://github.com/c3JpbmkK/turbo-octo-dollop/blob/main/clusters/{{name}}/{{path.basenameNormalized}}/values.yaml
      destination:
        name: in-cluster
        namespace: argocd
      syncPolicy:
        syncOptions:
        - CreateNamespace=true
        - ApplyOutOfSyncOnly=true
        - PrunePropagationPolicy=foreground
        automated:
          prune: true
          selfHeal: true
          allowEmpty: true
