apiVersion: v1
kind: ServiceAccount
metadata:
  name: '{{ .Release.Name }}-dns'
  namespace: '{{ .Release.Namespace }}'
  annotations:
    azure.workload.identity/client-id: '{{ .Values.dnsZoneContributorIdentity }}'
    azure.workload.identity/tenant-id: '{{ .Values.dnsZoneContributorTenant }}'
    helm.sh/hook: post-install, post-upgrade
    helm.sh/hook-delete-policy: hook-succeeded
  labels:
    azure.workload.identity/use: "true"
automountServiceAccountToken: true