apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: dns-role
  namespace: ingress-nginx
  # namespace: '{{ .Release.Namespace }}'
  annotations:
    helm.sh/hook: post-install
    helm.sh/hook-delete-policy: hook-succeeded
rules:
  - apiGroups:
    - ""
    resources:
      - namespaces
    verbs:
      - get
  - apiGroups:
    - ""
    resources:
    - services
    verbs:
    - get
    - list
     