apiVersion: v1
kind: ServiceAccount
metadata:
  name: '{{ .Release.Name }}-dns'
  namespace: '{{ .Release.Namespace }}'
  labels:
    azure.workload.identity/use: "true"
  annotations:
    azure.workload.identity/client-id: {{ .Values.dnsZoneContributorIdentity }}
    helm.sh/hook: post-install
    helm.sh/hook-delete-policy: hook-succeeded
automountServiceAccountToken: true