apiVersion: v1
kind: ServiceAccount
metadata:
  name: '{{ .Release.Name }}-dns'
  namespace: '{{ .Release.Namespace }}'
  annotations:
    helm.sh/hook: post-install
    helm.sh/hook-delete-policy: hook-succeeded
automountServiceAccountToken: true