apiVersion: batch/v1
kind: Job
metadata:
  name: '{{ .Release.Name }}-dns'
  namespace: '{{ .Release.Namespace }}'
  annotations:
    helm.sh/hook: post-install
    helm.sh/hook-delete-policy: hook-succeeded
spec:
  completionMode: NonIndexed
  backoffLimit: 1
  completions: 1
  parallelism: 1
  suspend: false
  ttlSecondsAfterFinished: 10
  template:
    spec:
      serviceAccountName: '{{ .Release.Name }}-dns'
      automountServiceAccountToken: true
      containers:
      - name: kubectl
        image: bitnami/kubectl:1.24.9
        command:
          - sleep
          - inf
      restartPolicy: Never   
