apiVersion: batch/v1
kind: Job
metadata:
  name: '{{ .Release.Name }}-lb'
  namespace: '{{ .Release.Namespace }}'
  annotations:
    helm.sh/hook: post-install, post-upgrade
    helm.sh/hook-delete-policy: hook-succeeded
spec:
  completionMode: NonIndexed
  backoffLimit: 1
  completions: 1
  parallelism: 1
  suspend: false
  ttlSecondsAfterFinished: 300
  template:
    metadata:
      annotations:
        azure.workload.identity/use: 'true'
      labels:
        azure.workload.identity/use: 'true'
    spec:
      serviceAccountName: '{{ .Release.Name }}-lb'
      automountServiceAccountToken: true
      containers:
      - name: azure-cli
        image: mcr.microsoft.com/azure-cli:latest
        env:
          - name: INGRESS_CONTROLLER_SERVICE
            value: 'ingress-nginx-controller'
          - name: INGRESS_PUBLIC_IP
            value: '13.80.101.179'
        command:
          - sh
          - -c
          - |
            #!/usr/bin/env bash

            # Setup kubectl cli
            az aks install-cli

            # Get IP address of the nginx loadbalancer service
            kubectl patch "svc/${INGRESS_CONTROLLER_SERVICE}" -p '{"spec":{"loadBalancerIP":"${INGRESS_PUBLIC_IP}"}}'
            sleep inf
            # Add new record to the DNS zone
      restartPolicy: Never
