apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: '{{ .Release.Name }}-lb'
  namespace: '{{ .Release.Namespace }}'
  annotations:
    helm.sh/hook: post-install, post-upgrade
    helm.sh/hook-delete-policy: hook-succeeded
subjects:
- kind: ServiceAccount
  name: '{{ .Release.Name }}-lb'
  namespace: '{{ .Release.Namespace }}'
roleRef:
  kind: Role
  name: '{{ .Release.Name }}-lb'
  apiGroup: rbac.authorization.k8s.io
