apiVersion: v2
version: "0.0.1"
name: cert-manager
description: Helm chart for cert-manager
home: https://github.com/cert-manager/cert-manager
icon: https://raw.githubusercontent.com/cert-manager/cert-manager/d53c0b9270f8cd90d908460d69502694e1838f5f/logo/logo-small.png
keywords:
  - cert-manager
  - kube-lego
  - letsencrypt
  - tls
sources:
  - https://github.com/cert-manager/cert-manager
dependencies:
  - name: cert-manager
    version: "v1.11.0"
    repository: https://charts.jetstack.io
