apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: tracer-certmanager
  namespace: argocd
  # WARNING: DELETION WILL PROPAGATE IF THIS FINALIZER IS USED
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: tracer
  source:
    repoURL: 'https://charts.jetstack.io'
    targetRevision: v1.11.0
    chart: cert-manager
    helm:
      parameters:
        - name: installCRDs
          value: 'true'
          forceString: true
  destination:
    name: tracer
    namespace: cert-manager
  syncPolicy:
    syncOptions:
    - CreateNamespace=true
    - ApplyOutOfSyncOnly=true
    - RespectIgnoreDifferences=true
    # WARNING: DELETION WILL PROPAGATE IF THIS OPTION IS USED TOGETHER WITH FINALIZER
    - PrunePropagationPolicy=foreground
    automated:
      prune: true
      selfHeal: true
  ignoreDifferences:
  - group: 'admissionregistration.k8s.io'
    kind: 'ValidatingWebhookConfiguration'
    name: tracer-certmanager-cert-manager-webhook
    jsonPointers:
    - /webhooks/*/namespaceSelector/matchExpressions/*