apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cert-manager
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    name: tracer
    namespace: cert-manager
  source:
    path: ''
    repoURL: 'https://charts.jetstack.io'
    targetRevision: v1.11.0
    chart: cert-manager
    helm:
      parameters:
      - name: "installCRDs"
        value: "true"
  sources: []
  project: tracer
  syncPolicy:
    syncOptions:
    - CreateNamespace=true
    - ApplyOutOfSyncOnly=true
    - PrunePropagationPolicy=foreground
    automated:
      prune: true
      selfHeal: true
      allowEmpty: true
