apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: tracer-certmanager
  namespace: argocd
  # WARNING: DELETION WILL PROPAGATE IF THIS FINALIZER IS USED
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: tracer
  source:
    repoURL: 'https://charts.jetstack.io'
    targetRevision: v1.11.0
    chart: cert-manager
    helm:
      parameters:
        - installCRDs: true
  destination:
    name: tracer
    namespace: cert-manager
  syncPolicy:
    syncOptions:
    - CreateNamespace=true
    - ApplyOutOfSyncOnly=true
    - PrunePropagationPolicy=foreground
    - RespectIgnoreDifferences=true
    automated:
      prune: true
      selfHeal: true
  ignoreDifferences:
  - group: 'admissionregistration.k8s.io'
    kind: 'ValidatingWebhookConfiguration'
    jsonPointers:
    - /webhooks/ #*/admissionReviewVersions/namespaceSelector