apiVersion: v2
version: "0.0.1"
name: crossplane
description: Crossplane is an open source Kubernetes add-on that enables platform teams to assemble infrastructure from multiple vendors, and expose higher level self-service APIs for application teams to consume.
home: https://crossplane.io
sources:
  - https://github.com/crossplane/crossplane
  - https://github.com/crossplane/crossplane-runtime
  - https://github.com/crossplane/provider-aws
  - https://github.com/crossplane/provider-azure
  - https://github.com/crossplane/provider-gcp
  - https://github.com/crossplane/provider-rook
keywords:
  - cloud
  - infrastructure
  - services
  - application
  - database
  - cache
  - bucket
  - infra
  - app
  - ops
  - gcp
  - azure
  - aws
  - alibaba
  - cloudsql
  - rds
  - s3
  - azuredatabase
  - asparadb
  - gke
  - aks
  - eks
