# Values file for ingress-nginx

# todo: Use correct cluster name
clusterName: tracer

dnsZoneName: cluster.sysctls.de

dnsZoneResourceGroup: cluster.sysctls.de

nginx:
  defaultBackend:
    enabled: true
  controller:
    resources:
      limits:
        cpu: 1
        memory: 1Gi
      requests:
        cpu: 500m
        memory: 500Mi
    autoscaling:
      enabled: false
      maxReplicas: 5
      minReplicas: 1
      targetCPUUtilizationPercentage: 50
      targetMemoryUtilizationPercentage: 50
