apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: in-cluster-argocd
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "3"
  labels:
    app: argocd
    cluster: in-cluster
    topology.kubernetes.io/region: local
  # WARNING: DELETION WILL PROPAGATE IF THIS FINALIZER IS USED
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: in-cluster
  source:
    repoURL: 'https://github.com/c3JpbmkK/turbo-octo-dollop'
    targetRevision: '5-mono'
    path: charts/argocd
    helm:
      valueFiles:
        - values.yaml
  destination:
    name: in-cluster
    namespace: argocd
  syncPolicy:
    syncOptions:
    - CreateNamespace=true
    - ApplyOutOfSyncOnly=true
    # WARNING: DELETION WILL PROPAGATE IF THIS OPTION IS USED TOGETHER WITH FINALIZER
    - PrunePropagationPolicy=foreground
    automated:
      prune: true
      selfHeal: true