# Values file for ingress-nginx

defaultBackend:
  enabled: true
controller:
  config:
    data:
      enable-opentracing: "true"
      jaeger-collector-host: jaeger-agent.jaeger.svc
  resources:
    limits:
      cpu: 1
      memory: 1Gi
    requests:
      cpu: 500m
      memory: 500Mi
  autoscaling:
    enabled: false
  opentelemetry:
    enabled: true
