apiVersion: v2
version: "0.0.1"
name: ingress-nginx
description: Ingress controller for Kubernetes using NGINX as a reverse proxy and load balancer
home: https://github.com/kubernetes/ingress-nginx
keywords:
  - ingress
  - nginx
sources:
  - https://github.com/kubernetes/ingress-nginx
dependencies:
  - name: ingress-nginx
    version: "4.5.2"
    repository: "https://kubernetes.github.io/ingress-nginx"
    alias: nginx
