apiVersion: network.azure.upbound.io/v1beta1
kind: DNSZone
metadata:
  annotations:
    # argocd.argoproj.io/hook: Sync
    argocd.argoproj.io/sync-wave: "1"
    crossplane.io/external-name: {{ .Release.Name }}.{{ .Values.clusterDomain }}
  labels:
    network.azure.upbound.io/dnsZone: {{ .Release.Name }}
  name: {{ .Release.Name }}
spec:
  deletionPolicy: {{ .Values.deletionPolicy }}
  forProvider:
    resourceGroupNameSelector:
      matchLabels:
        azure.upbound.io/resourceGroup: {{ .Release.Name }}
  providerConfigRef:
    name: {{ .Values.providerConfig.name }}
