apiVersion: network.azure.upbound.io/v1beta1
kind: DNSZone
metadata:
  annotations:
    crossplane.io/external-name: '{{ .Values.clusterDomain }}'
  name: '{{ .Release.Name }}'
spec:
  forProvider:
    resourceGroupName: '{{ .Release.Name }}'
  providerConfigRef:
    name: '{{ .Release.Name }}'