apiVersion: containerservice.azure.upbound.io/v1beta1
kind: KubernetesCluster
metadata:
  name: {{ .Release.Name }}
  labels:
    containerservice.azure.upbound.io/kubernetesCluster: {{ .Release.Name }}
spec:
  forProvider:
    defaultNodePool:
      - name: default
        nodeCount: 1
        vmSize: Standard_DS2_v2
        podSubnetIdSelector: 
          matchLabels:
            network.azure.upbound.io/subnet: default
    dnsPrefix: {{ .Release.Name }}
    identity:
      - type: SystemAssigned
    location: {{ .Values.location }}
    resourceGroupNameSelector:
      matchLabels:
        azure.upbound.io/resourceGroup: {{ .Release.Name }}
  providerConfigRef:
    name: {{ .Values.providerConfig.name }}
  writeConnectionSecretToRef:
    name: '{{ .Release.Name }}-connection-secret'
    namespace: crossplane-system