# https://helm.sh/docs/chart_template_guide/variables/
{{- $ReleaseName := .Release.Name -}}
{{- $ProviderName := .Values.providerConfig.name }}
{{- range $nodePool := .Values.additionalNodePools }}
---
apiVersion: containerservice.azure.upbound.io/v1beta1
kind: KubernetesClusterNodePool
metadata:
  labels:
    containerservice.azure.upbound.io/kubernetesCluster: {{ $nodePool.name }}
  name: {{ $nodePool.name }}
spec:
  forProvider:
    node: {{ $nodePool.mode }}
    kubernetesClusterIdSelector:
      matchLabels:
        containerservice.azure.upbound.io/kubernetesCluster: {{ $ReleaseName }}
    nodeCount: {{ $nodePool.nodeCount }}
    vmSize: {{ $nodePool.vmSize }}
    podSubnetIdSelector: 
      matchLabels:
        network.azure.upbound.io/subnet: {{ $nodePool.subnet }}
    vnetSubnetIdSelector: 
      matchLabels:
        network.azure.upbound.io/subnet: {{ $nodePool.subnet }}
  providerConfigRef:
    name: {{ $ProviderName }}

{{- end }}