apiVersion: containerservice.azure.upbound.io/v1beta1
kind: KubernetesCluster
metadata:
  name: {{ .Release.Name }}
  labels:
    kubernetesCluster: {{ .Release.Name }}
spec:
  forProvider:
    defaultNodePool:
      - name: default
        nodeCount: 1
        vmSize: Standard_DS2_v2
    dnsPrefix: {{ .Release.Name }}
    identity:
      - type: SystemAssigned
    location: {{ .Values.location }}
    resourceGroupName: {{ .Release.Name }}
  providerConfigRef:
    name: {{ .Values.providerConfig }}
  writeConnectionSecretToRef:
    name: '{{ .Release.Name }}-connection-secret'
    namespace: crossplane-system