apiVersion: containerservice.azure.upbound.io/v1beta1
kind: KubernetesCluster
metadata:
  annotations:
    argocd.argoproj.io/sync-wave: "3"
  labels:
    containerservice.azure.upbound.io/kubernetesCluster: {{ .Release.Name }}
  name: {{ .Release.Name }}
spec:
  forProvider:
    skuTier: {{ .Values.kubernetesCluster.skuTier }}
    defaultNodePool:
      - name: default
        enableAutoScaling: true
        minCount: 1
        maxCount: 5
        vmSize: Standard_D4s_v3
        vnetSubnetIdSelector: 
          matchLabels:
            network.azure.upbound.io/subnet: default
    oidcIssuerEnabled: {{ .Values.kubernetesCluster.oidcIssuerEnabled }}
    workloadIdentityEnabled: {{ .Values.kubernetesCluster.workloadIdentityEnabled }}
    networkProfile: 
    - networkPlugin: {{ .Values.kubernetesCluster.networkProfile.networkPlugin }}
      networkPolicy: {{ .Values.kubernetesCluster.networkProfile.networkPolicy }}
      dockerBridgeCidr: {{ .Values.kubernetesCluster.networkProfile.dockerBridgeCidr }}
      dnsServiceIp: {{ .Values.kubernetesCluster.networkProfile.dnsServiceIp }}
      serviceCidr: {{ .Values.kubernetesCluster.networkProfile.serviceCidr }}
    dnsPrefix: {{ .Release.Name }}
    identity:
      - type: SystemAssigned
    location: {{ .Values.location }}
    resourceGroupNameSelector:
      matchLabels:
        azure.upbound.io/resourceGroup: {{ .Release.Name }}
  providerConfigRef:
    name: {{ .Values.providerConfig.name }}
  writeConnectionSecretToRef:
    name: '{{ .Release.Name }}-connection-secret'
    namespace: {{ .Release.Namespace }}