apiVersion: containerservice.azure.upbound.io/v1beta1
kind: KubernetesCluster
metadata:
  name: '{{ .Release.Name }}'
spec:
  forProvider:
    defaultNodePool:
      - name: default
        nodeCount: 1
        vmSize: Standard_D4s_v3
    dnsPrefix: '{{ .Release.Name }}'
    identity:
      - type: SystemAssigned
    location: '{{ .Values.location }}'
    resourceGroupName: '{{ .Release.Name }}'
  providerConfigRef:
    name: '{{ .Release.Name }}'
  writeConnectionSecretToRef:
    name: '{{ .Release.Name }}-connection-secret'
    namespace: crossplane-system