apiVersion: containerservice.azure.upbound.io/v1beta1
kind: KubernetesClusterNodePool
metadata:
  labels:
    testing.upbound.io/example-name: example
  name: example
spec:
  forProvider:
    kubernetesClusterIdSelector:
      matchLabels:
        testing.upbound.io/example-name: example
    nodeCount: 1
    tags:
      Environment: Production
    vmSize: Standard_DS2_v2
