{{- range $nodePool := .Values.nodePools }}
---
apiVersion: containerservice.azure.upbound.io/v1beta1
kind: KubernetesClusterNodePool
metadata:
  labels:
    kubernetesCluster: '{{ .Release.Name }}'
  name: {{ $nodePool.name }}
spec:
  forProvider:
    kubernetesClusterIdSelector:
      matchLabels:
        kubernetesCluster: '{{ .Release.Name }}'
    nodeCount: ${{ $nodePool.nodeCount }}
    vmSize: ${{ $nodePool.vmSize }}
  providerConfigRef:
    name: '{{ .Release.Name }}'

{{- end }}