apiVersion: azure.upbound.io/v1beta1
kind: ProviderConfig
metadata:
  name:  {{ .Release.Name }}
spec:
  credentials:
    source: Secret
    secretRef:
      namespace: crossplane-system
      name: {{ .Values.providerConfigSecret.name }}
      key: {{ .Values.providerConfigSecret.key }}
