# https://helm.sh/docs/chart_template_guide/variables/
{{- $ReleaseName := .Release.Name -}}
{{- $ProviderName := .Values.providerConfig.name }}
{{- if .Values.virtualNetwork.subnets }}
{{- range $subnet := .Values.virtualNetwork.subnets }}
---
apiVersion: network.azure.upbound.io/v1beta1
kind: Subnet
metadata:
  name: {{ $subnet.name }}
  labels:
    network.azure.upbound.io/subnet: {{ $subnet.name }}
spec:
  forProvider:
    addressPrefixes:
      - {{ $subnet.addressPrefix }}
    resourceGroupNameSelector:
      matchLabels:
        azure.upbound.io/resourceGroup: {{ $ReleaseName }}
      virtualNetworkNameSelector:
        matchLabels:
          network.azure.upbound.io/virtualNetwork: {{ $ReleaseName }}
  providerConfigRef:
    name: {{ $ProviderName }}

{{- end }}
{{- else }}
---
  apiVersion: network.azure.upbound.io/v1beta1
  kind: Subnet
  metadata:
    name: default
    labels:
      network.azure.upbound.io/subnet: default
  spec:
    forProvider:
      addressPrefixes:
        - "10.0.0.0/24"
      resourceGroupNameSelector:
        matchLabels:
          azure.upbound.io/resourceGroup: {{ $ReleaseName }}
      virtualNetworkNameSelector:
        matchLabels:
          network.azure.upbound.io/virtualNetwork: {{ $ReleaseName }}
    providerConfigRef:
      name: {{ $ProviderName }}
{{- end }}