apiVersion: managedidentity.azure.upbound.io/v1beta1
kind: UserAssignedIdentity
metadata:
  annotations:
    argocd.argoproj.io/hook: Sync
    argocd.argoproj.io/sync-wave: "2"
  labels:
    managedidentity.azure.upbound.io/userAssignedIdentity: {{ .Release.Name }}
  name: {{ .Release.Name }}
spec:
  deletionPolicy: {{ .Values.deletionPolicy }}
  forProvider:
    location: {{ .Values.location }}
    name: {{ .Release.Name }}
    resourceGroupNameSelector:
      matchLabels:
        azure.upbound.io/resourceGroup: {{ .Release.Name }}
  providerConfigRef:
    name: {{ .Values.providerConfig.name }}