# Values file for westeurope-cluster-00

deletionPolicy: Delete

providerConfig: 
  name: azure-providerconfig

location: West Europe

clusterName: westeurope-cluster-00
clusterDomain: clusters.sysctls.de

# todo: peer two vnets
# chore: identify how to connect to vnets, either using single provider config or two
virtualNetwork:
  addressSpace: 10.64.0.0/16
  subnets:
    - name: default
      addressPrefix: 10.64.4.0/22
    - name: infrapool
      addressPrefix: 10.64.8.0/22
    - name: workloadpool
      addressPrefix: 10.64.12.0/22

publicIP:
  allocationMethod: Static
  sku: Standard
  apps:
    - argocd
    - jaeger
    - grafana
    - oauth2-proxy

kubernetesCluster:
  skuTier: Free
  networkProfile:
    networkPlugin: azure
    networkPolicy: calico
    dnsServiceIp: 10.64.0.10
    serviceCidr: 10.64.0.0/23
    dockerBridgeCidr: 172.16.0.0/16
  oidcIssuerEnabled: true
  workloadIdentityEnabled: true

additionalNodePools:
  - name: infrapool
    subnet: infrapool
    mode: User
    vmSize: Standard_D4s_v3
    nodeCount: 1
    enableAutoScaling: true
    minCount: 1
    maxCount: 5
  - name: workloadpool
    subnet: workloadpool
    mode: User
    vmSize: Standard_D4s_v3
    nodeCount: 1
    enableAutoScaling: false
    minCount: 1
    maxCount: 5
