# Values file for westeurope-cluster-00

deletionPolicy: Delete

providerConfigSecret: 
  name: azure-providerconfig
  key: creds

location: West Europe

clusterName: westeurope-cluster-00
clusterDomain: clusters.sysctls.de

virtualNetwork:
  addressSpace: 10.64.0.0/16
  subnets:
    - name: default
      addressPrefix: 10.64.0.0/22
    - name: infrapool
      addressPrefix: 10.64.4.0/22
    - name: workloadpool
      addressPrefix: 10.64.8.0/22

additionalNodePools:
  - name: infrapool
    mode: User
    vmSize: Standard_D4s_v3
    nodeCount: 1
  - name: workloadpool
    mode: User
    vmSize: Standard_D4s_v3
    nodeCount: 1
