# Values file for argocd

server:
  ingress:
    enabled: true
    annotations:
      nginx.ingress.kubernetes.io/enable-opentracing: "true"
      cert-manager.io/cluster-issuer: cert-manager-http01
    hosts:
      - argocd.westeurope-cluster-00.clusters.sysctls.de
    tls: 
      - secretName: argocd-server-tls
        hosts:
          - argocd.westeurope-cluster-00.clusters.sysctls.de